/* tileset_atlas.h - Generated by extract_tiles.py. Do not edit directly. */
#ifndef TILESET_ATLAS_H
#define TILESET_ATLAS_H

#define TILE_SIZE 16
#define TILES_PER_ROW 32
#define TOTAL_TILES 969
#define ATLAS_WIDTH 512
#define ATLAS_HEIGHT 512

/* Sprites & Toolbar Tile IDs */
#define SPRITE_TRAIN_TILE    960
#define SPRITE_COPTER_TILE   961
#define SPRITE_PLANE_TILE    962
#define SPRITE_SHIP_TILE     963
#define SPRITE_MONSTER_TILE  964
#define SPRITE_TORNADO_TILE  965
#define TOOLBAR_VILLA_TILE   966
#define TOOLBAR_SHOP_TILE    967
#define TOOLBAR_FACTORY_TILE 968

static inline int tile_atlas_x(int tile_id) {
  return (tile_id % 32) * 16;
}

static inline int tile_atlas_y(int tile_id) {
  return (tile_id / 32) * 16;
}

#endif /* TILESET_ATLAS_H */
