/* Generated by prep_assets.py: native Playdate button glyphs - do not edit */
#ifndef UI_GLYPHS_H
#define UI_GLYPHS_H

enum {
    GLYPH_A,
    GLYPH_B,
    GLYPH_DPAD,
    GLYPH_UP,
    GLYPH_RIGHT,
    GLYPH_DOWN,
    GLYPH_LEFT,
    GLYPH_CRANK,
    GLYPH_MENU,
    GLYPH_COUNT
};

#define GLYPH_W 20
#define GLYPH_H 20
static const int k_glyph_advance[GLYPH_COUNT] = { 18, 18, 18, 18, 18, 18, 18, 20, 20 };

#endif
